spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/aplicacao
    username: root
    password: 1234
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/